#!/bin/bash

total=0
opt_file=opt_tsp

compile(){
    echo "Compiling..."
    make -C ./src
    make -C ./tester
}

tester-bf(){
    files=$(find ./testcases/bf-cases -type f | sort -V)
    resp="y"
    for file in $files; do
        if [ "./testcases/bf-cases/11.g" == $file ]; then
            echo -e "\n---Warning----"
            echo -e "The next test cases need about 45gb of memory"
            echo -e "Do you want to proceed? [y/n]: "
            read -r resp
        fi;
        if [ $resp == "y" ]; then
            execute "bf" $file 
        fi;
    done
}

execute(){
    printf "%-4s %-30s: " $1 $2
    init=$(date +%s%3N)
    result=$(./src/prog.out $1 $2 $3 $4 $5)
    let end=$(date +%s%3N)-$init
    let ms=$end%1000
    let sec=$end/1000
    let min=$sec/60
    let sec=$sec%60
    let total=$total+$end
    echo $result | ./tester/tester.out $2
    filename=$(echo $2 | cut -d '/' -f4 | cut -d '.' -f1)
    opt_cost=$(get_opt $filename)
    printf "(%'dm %'ds %'dms) best: %s\n" $min $sec $ms $opt_cost
}

get_opt(){
    while read i; do
        name=$(echo $i | cut -d ' ' -f1)
        cost=$(echo $i | cut -d ' ' -f3)
        if [ "$1" == "$name" ]; then
            echo $cost
        fi
    done < $opt_file
}

tester(){
    files=$(find ./testcases/tsp -type f | sort -V)
    total=0
    for file in $files; do
        execute $1 $file $2 $3 $4
    done
    let ms=$total%1000
    let sec=$total/1000
    let min=$sec/60
    let sec=$sec%60
    printf "(%'dm %'ds %'dms)\n" $min $sec $ms
}

algs=(nn mst ga csp) 

case $1 in
"" | "all")
    for alg in ${algs[@]}; do
        tester $alg $2 $3 $4
    done
    ;;

nn)
    tester ${algs[0]}
    ;;

mst)
    tester ${algs[1]}
    ;;

ga)
    tester ${algs[2]} $2 $3 $4
    ;;

csp)
    tester ${algs[3]}
    ;;

bf)
    tester-bf
    ;;


build)
    compile

esac
